export const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHtml;
export const totalScore = criteria => criteria.length === 7 && criteria.every(c => typeof c.score === 'number') ? criteria.reduce((sum,c) => sum + c.score, 0) : null;
const external = (url, label, cls='text-link') => `<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)} <span aria-hidden="true">↗</span></a>`;
export function renderProjects(finalistes) {
  return finalistes.map((p,i) => `<article class="project" id="${e(p.id.toLowerCase())}"><div class="project-top"><span class="project-id">${e(p.id)}</span><span class="status">${p.publication ? 'Dossier publié' : 'Dossier à venir'}</span></div>${p.preview ? `<a class="project-preview" href="${e(p.preview.sourceUrl)}" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="${e(p.preview.src)}" alt="${e(p.preview.alt)}" width="1200" height="750" /><span>Capture du ${e(p.preview.capturedAt)}</span></a>` : `<div class="project-awaiting"><span class="axis-number" aria-hidden="true">0${i+1}</span><span>${e(p.axis)}</span></div>`}<div class="project-body"><p class="project-profile">${e(p.profile)}</p><h3>${e(p.name)}</h3><p class="project-title">${e(p.title || p.axis)}</p><p>${e(p.summary || 'Le dossier de présentation, les liens et l’aperçu seront ajoutés après vérification.')}</p><div class="project-links">${p.pagesUrl ? external(p.pagesUrl,'Voir la page du projet','button button-small') : ''}${p.repositoryUrl ? external(p.repositoryUrl,'Ouvrir le dépôt') : ''}</div><details><summary>Consulter la fiche du dossier</summary><div class="project-detail">${p.evidence.length ? `<h4>Preuves publiées</h4><ul>${p.evidence.map(v=>`<li>${external(v.url,v.label)} <span class="muted">${e(v.type)}</span></li>`).join('')}</ul>` : `<h4>Pièces attendues</h4><ul><li>Portfolio et index de 6 à 10 preuves</li><li>Production principale et comparaison avant/après</li><li>Contribution personnelle et contrôles réalisés</li><li>Limite du projet et prochaine étape</li></ul>`}<p>${p.evaluation ? 'Synthèse validée disponible dans la section Résultats.' : 'Évaluation : synthèse non publiée.'}</p></div></details></div></article>`).join('');
}
export function renderCriteria(grille) {
  return grille.criteria.map(c=>`<article class="criterion"><span class="criterion-id">${e(c.id)}</span><div><h3>${e(c.label)}</h3><p>${e(c.indicator)}</p></div><div class="criterion-weight"><strong>${c.max}</strong><span>points</span></div></article>`).join('');
}
export function renderEvaluations(finalistes, grille) {
  const evaluated=finalistes.filter(p=>p.evaluation?.status==='validee');
  if (!evaluated.length) return `<div class="empty-results"><span class="empty-tag">SYNTHÈSES À VENIR</span><h3>Aucun rapport d’évaluation publié.</h3><p>Les dossiers seront analysés avec la même grille. Les résultats seront affichés après examen et validation du pilote.</p><a href="#grille" class="text-link">Consulter les sept critères ↑</a></div>`;
  return evaluated.map(p=>{const v=p.evaluation,total=totalScore(v.criteria);return `<article class="evaluation"><div class="evaluation-header"><div><span class="eyebrow">SYNTHÈSE VALIDÉE</span><h3>${e(p.name)}</h3></div><strong>${total===null?'Évaluation partielle':`${total} / 100`}</strong></div><p><b>Force démontrée :</b> ${e(v.strength)}</p><p><b>Prochaine action :</b> ${e(v.nextAction)}</p><details><summary>Lire les appréciations par critère</summary><div class="table-scroll"><table><caption>Grille ${e(v.gridVersion)}</caption><thead><tr><th scope="col">Critère</th><th scope="col">Appréciation</th><th scope="col">Points</th></tr></thead><tbody>${v.criteria.map(c=>`<tr><th scope="row">${e(grille.criteria.find(g=>g.id===c.id).label)}</th><td>${e(c.observation)}${c.evidenceUrls.length?`<ul>${c.evidenceUrls.map((url,i)=>`<li>${external(url,`Preuve ${i+1}`)}</li>`).join('')}</ul>`:''}</td><td>${c.score===null?'Non évalué':`${c.score} / ${grille.criteria.find(g=>g.id===c.id).max}`}</td></tr>`).join('')}</tbody></table></div></details><p class="muted">Validé par ${e(v.validatedBy)} · Publié le ${e(v.publishedAt)} · Décision ${e(v.decisionRef)}</p><a class="text-link" href="${e(v.reportPath)}" download>Télécharger la synthèse publique (.md) ↓</a></article>`}).join('');
}
export function renderAward(resultats, finalistes) {
  if(resultats.status!=='publie')return `<div><p class="eyebrow">GRAND PRIX LN-IA</p><h3>Une décision à documenter.</h3></div><p>Le lauréat sera annoncé après confirmation du règlement applicable et validation de la décision du pilote.</p>`;
  const winner=finalistes.find(p=>p.id===resultats.winnerId);
  return `<div><p class="eyebrow">GRAND PRIX LN-IA · DÉCISION VALIDÉE</p><h3>${e(winner.name)}</h3></div><div><p>${e(resultats.announcement)}</p><p>Décision ${e(resultats.decisionRef)} · Règlement ${e(resultats.rulesRef)}</p><p>Validation : ${e(resultats.validatedBy)}, le ${e(resultats.validatedAt)}</p></div>`;
}
